/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package buildship.sample.modulepath;

import java.io.Reader;
import java.io.StringReader;

import org.yaml.snakeyaml.Yaml;

public class Main {
    public static void main(String[] args) {
		Yaml yaml = new Yaml();
		Reader reader = new StringReader("foo=bar");		
		System.out.println(yaml.parse(reader));
	}
}
